- name: add Postgres servers to inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add pg1 to inventory
      add_host:
        name: pg1
        ansible_host: 192.168.1.241
        groups: postgres
    - name: Add pg2 to inventory
      add_host:
        name: pg2
        ansible_host: 192.168.1.242
        groups: postgres

- name: Deploy PostgreSQL pg_hba.conf
  hosts: postgres
  become: true
  #the user on the pg nodes that has sudo access w/o a password prompt
  remote_user: fnord

  vars:
    #location from the machine you are running the ansible playbook from
    ansible_ssh_private_key_file: /home/fnord/.ssh/ansible_id_rsa
    #don't check thumbprints
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    # Host connection mappings
    ansible_host_map:
      pg1: 192.168.1.241
      pg2: 192.168.1.242

    # Host roles
    is_primary_map:
      pg1: true
      pg2: false

    replication_user:
      name: replicator
      cidr: 192.168.1.242/32

    users:
      - name: pgadmin
        cidr: 0.0.0.0/0

    trusted_networks:
      - 192.168.7.0/24
      - 10.10.0.0/16
      
  tasks:
    - name: Set ansible_host and is_primary dynamically
      set_fact:
        ansible_host: "{{ ansible_host_map[inventory_hostname] }}"
        is_primary: "{{ is_primary_map[inventory_hostname] }}"

    - name: Deploy pg_hba.conf
      template:
        src: templates/pg_hba.conf.j2
        dest: /etc/postgresql/16/main/pg_hba.conf
        owner: postgres
        group: postgres
        mode: '0600'
      notify: Reload PostgreSQL

  handlers:
    - name: Reload PostgreSQL
      systemd:
        name: postgresql
        state: reloaded